### ISSUE TITLE
Error when running npm run build

### ISSUE THREAD

**Issue by atrotter0** [atrotter0/javascript-project-config-tool#3]
Encountering some dependency issues when running `npm run build` after tool clones and configures new project.

Example output after attempt to use the tool: 

```
TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/abeltrotter/Desktop/noob/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /Users/abeltrotter/Desktop/noob/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/Users/abeltrotter/Desktop/noob/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@1.0.0 build: `webpack --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by atrotter0** [comment]
Fixed by https://github.com/atrotter0/javascript-project-config-tool/pull/4
